[package]
name = "zluda"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2021"

[lib]
name = "nvcuda"
crate-type = ["cdylib", "staticlib"]

[features]
default = ["intel"]
intel = ["flate2", "dep:ze_runtime_sys", "ptx_backend", "comgr?/intel", "cuda_types/intel", "ptx?/intel"]
amd = ["dep:hip_runtime_sys", "ptx_backend", "comgr?/amd", "cuda_types/amd", "ptx?/amd"]
tenstorrent = ["dep:tt_runtime_sys", "dep:tt_comgr_sys", "ptx_backend", "comgr?/tenstorrent", "ptx?/tenstorrent"]
gemmini = []
nvidia = ["dep:nvidia_runtime_sys"]
tmatmul = ["ptx_backend"]
pacc = []
webgpu = []
cutile = ["dep:cutile_comgr_sys", "ptx_backend", "comgr?/cutile"]
ane = ["tmatmul"]
embed_cudart = []
flate2 = ["dep:flate2"]
ptx_backend = ["dep:comgr", "dep:ptx", "dep:ptx_parser"]

[dependencies]
comgr = { path = "../comgr", default-features = false, optional = true }
ptx_parser = { path = "../ptx_parser", optional = true }
ptx = { path = "../ptx", default-features = false, optional = true }
cuda_types = { path = "../cuda_types", default-features = false }
cuda_base = { path = "../cuda_base" }
lazy_static = "1.4"
num_enum = "0.4"
lz4-sys = "1.9"
tempfile = "3"
paste = "1.0"
rustc-hash = "1.1"
ze_runtime_sys = { path = "../ext/ze_runtime-sys", optional = true }
hip_runtime_sys = { path = "../ext/hip_runtime-sys", optional = true }
tt_runtime_sys = { path = "../ext/tt_runtime-sys", optional = true }
tt_comgr_sys = { path = "../ext/tt_comgr-sys", optional = true }
cutile_comgr_sys = { path = "../ext/cutile_comgr-sys", optional = true }
nvidia_runtime_sys = { path = "../ext/nvidia_runtime-sys", optional = true }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = { version = "1.0", optional = true }

[build-dependencies]
cc = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["heapapi", "std"] }
